// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	api "TopKScores/api"

	mock "github.com/stretchr/testify/mock"
)

// TopKScoreProvider is an autogenerated mock type for the TopKScoreProvider type
type TopKScoreProvider struct {
	mock.Mock
}

// AddScore provides a mock function with given fields: gameScore
func (_m *TopKScoreProvider) AddScore(gameScore *api.GameScore) error {
	ret := _m.Called(gameScore)

	var r0 error
	if rf, ok := ret.Get(0).(func(*api.GameScore) error); ok {
		r0 = rf(gameScore)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTopKScores provides a mock function with given fields: k
func (_m *TopKScoreProvider) GetTopKScores(k int64) ([]*api.GameScore, error) {
	ret := _m.Called(k)

	var r0 []*api.GameScore
	if rf, ok := ret.Get(0).(func(int64) []*api.GameScore); ok {
		r0 = rf(k)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.GameScore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(k)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTopKScoreProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewTopKScoreProvider creates a new instance of TopKScoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTopKScoreProvider(t mockConstructorTestingTNewTopKScoreProvider) *TopKScoreProvider {
	mock := &TopKScoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
